### PR TITLE
Create subprojects/libplacebo.wrap(auto-pull dep)

### PR DESCRIPTION
**Pull request by jimman2003**
Tested locally..
Pulling and configuring works for me(of course not building..)
See:https://mesonbuild.com/Wrap-dependency-system-manual.html

### CODE REVIEW

**Comment by jimman2003** [comment]
It needs to clone libplacebo 1st then wipe meson build and then it works @Dudemanguy (for me)

**Comment by jimman2003** [comment]
The current .gitignore should change to include libplacebo.wrap to git

**Comment by Dudemanguy** [comment]
I mean I appreciate the interest but the PR is very much WIP and unstable. I'm going to constantly force push to it and change stuff (e.g. I fixed subproject building earlier today) so I'm not really sure I see the point in opening PRs against my branch? Feel free to leave any comments/feedback on the main PR on mpv of course though.

**Comment by Dudemanguy** [comment]
Way late here, but I am going to close this of course. We aren't going to use *.wrap files for mpv and the PR is way different now.

**Pull request closed without merging**
